#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "yanosea"
email = "81510859+yanosea@users.noreply.github.com"

[ui]
default-command = "log"
pager = "delta"
diff.tool = ["delta", "--color-only"]
color = "auto"

[git]
colocate = true

[signing]
backend = "gpg"
key = "B8C069E2833A7A32"
sign-all = true
