format = """
[░▒▓](#83c092)\
$os\
[](bg:#a7c080 fg:#83c092)\
$directory\
[](fg:#a7c080 bg:#2E383C)\
${custom.jj}\
[](fg:#2E383C bg:#374145)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#374145 bg:#2E383C)\
$time\
[ ](fg:#2E383C)\
\n$character"""

[os]
format = "[ $symbol ]($style)"
style = "bg:#83c092 fg:#272E33"
disabled = false

[os.symbols]
Windows = ""
Arch = ""
Macos = ""
NixOS = ""

[directory]
style = "fg:#7A8478 bg:#a7c080"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
disabled = true

[git_status]
disabled = true

[nodejs]
symbol = ""
style = "bg:#374145"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#374145)]($style)'

[rust]
symbol = ""
style = "bg:#374145"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#374145)]($style)'

[golang]
symbol = ""
style = "bg:#374145"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#374145)]($style)'

[php]
symbol = ""
style = "bg:#374145"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#374145)]($style)'

[time]
disabled = false
time_format = "%H:%M:%S"
style = "bg:#2E383C"
format = '[[   $time ](fg:#d3c6aa bg:#2E383C)]($style)'

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship"]
style = "bg:#2E383C"
format = '[[ $output ](fg:#a7c080 bg:#2E383C)]($style)'
