format = """
[░▒▓](#83c092)\
$os\
[](bg:#a7c080 fg:#83c092)\
$directory\
[](fg:#a7c080 bg:#343f44)\
$nodejs\
$rust\
$golang\
$php\
${custom.nix}\
[](fg:#343f44 bg:#2d353b)\
${custom.jj}\
${custom.git}\
$time\
\n$character"""

[os]
format = "[ $symbol ]($style)"
style = "bg:#83c092 fg:#2d353b"
disabled = false

[os.symbols]
Windows = ""
Arch = ""
Macos = ""
NixOS = ""

[directory]
style = "fg:#2d353b bg:#a7c080"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
disabled = true

[git_status]
disabled = true

[nodejs]
symbol = ""
style = "bg:#343f44"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#343f44)]($style)'

[rust]
symbol = ""
style = "bg:#343f44"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#343f44)]($style)'

[golang]
symbol = ""
style = "bg:#343f44"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#343f44)]($style)'

[php]
symbol = ""
style = "bg:#343f44"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#343f44)]($style)'

[time]
disabled = false
time_format = "%H:%M:%S"
style = "bg:#2d353b"
format = '[[   $time ](fg:#d3c6aa bg:#2d353b)]($style)'

[custom.jj]
when = "jj root 2>/dev/null"
command = "jj-starship"
style = "bg:#2d353b"
format = '[ $output ](fg:#a7c080 bg:#2d353b)'

[custom.git]
when = "! jj root 2>/dev/null && git rev-parse --is-inside-work-tree 2>/dev/null"
command = "echo \" $(git branch --show-current)$(git diff --quiet || echo ' !')$(git diff --cached --quiet || echo ' +')\" "
style = "bg:#2d353b"
format = '[[$output](fg:#a7c080 bg:#2d353b)]($style)'

[custom.nix]
when = "test -f flake.nix"
command = "echo \"  $(jq -r '.nodes.nixpkgs.locked.rev' flake.lock 2>/dev/null | head -c 7)\""
style = "bg:#343f44"
format = '[[ $output ](fg:#a7c080 bg:#343f44)]($style)'
